/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VisaRouteImport } from './routes/visa'
import { Route as UmrahRouteImport } from './routes/umrah'
import { Route as ToursRouteImport } from './routes/tours'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as MedicalTourismRouteImport } from './routes/medical-tourism'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AirTicketingRouteImport } from './routes/air-ticketing'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminVisaRequirementsRouteImport } from './routes/admin.visa-requirements'
import { Route as AdminVisaCountriesRouteImport } from './routes/admin.visa-countries'
import { Route as AdminSettingsRouteImport } from './routes/admin.settings'
import { Route as AdminPackagesRouteImport } from './routes/admin.packages'
import { Route as AdminLoginRouteImport } from './routes/admin.login'
import { Route as AdminInquiriesRouteImport } from './routes/admin.inquiries'

const VisaRoute = VisaRouteImport.update({
  id: '/visa',
  path: '/visa',
  getParentRoute: () => rootRouteImport,
} as any)
const UmrahRoute = UmrahRouteImport.update({
  id: '/umrah',
  path: '/umrah',
  getParentRoute: () => rootRouteImport,
} as any)
const ToursRoute = ToursRouteImport.update({
  id: '/tours',
  path: '/tours',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const MedicalTourismRoute = MedicalTourismRouteImport.update({
  id: '/medical-tourism',
  path: '/medical-tourism',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AirTicketingRoute = AirTicketingRouteImport.update({
  id: '/air-ticketing',
  path: '/air-ticketing',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminVisaRequirementsRoute = AdminVisaRequirementsRouteImport.update({
  id: '/admin/visa-requirements',
  path: '/admin/visa-requirements',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminVisaCountriesRoute = AdminVisaCountriesRouteImport.update({
  id: '/admin/visa-countries',
  path: '/admin/visa-countries',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/admin/settings',
  path: '/admin/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminPackagesRoute = AdminPackagesRouteImport.update({
  id: '/admin/packages',
  path: '/admin/packages',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin/login',
  path: '/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminInquiriesRoute = AdminInquiriesRouteImport.update({
  id: '/admin/inquiries',
  path: '/admin/inquiries',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/air-ticketing': typeof AirTicketingRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/medical-tourism': typeof MedicalTourismRoute
  '/services': typeof ServicesRoute
  '/tours': typeof ToursRoute
  '/umrah': typeof UmrahRoute
  '/visa': typeof VisaRoute
  '/admin/inquiries': typeof AdminInquiriesRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/packages': typeof AdminPackagesRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/visa-countries': typeof AdminVisaCountriesRoute
  '/admin/visa-requirements': typeof AdminVisaRequirementsRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/air-ticketing': typeof AirTicketingRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/medical-tourism': typeof MedicalTourismRoute
  '/services': typeof ServicesRoute
  '/tours': typeof ToursRoute
  '/umrah': typeof UmrahRoute
  '/visa': typeof VisaRoute
  '/admin/inquiries': typeof AdminInquiriesRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/packages': typeof AdminPackagesRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/visa-countries': typeof AdminVisaCountriesRoute
  '/admin/visa-requirements': typeof AdminVisaRequirementsRoute
  '/admin': typeof AdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/air-ticketing': typeof AirTicketingRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/medical-tourism': typeof MedicalTourismRoute
  '/services': typeof ServicesRoute
  '/tours': typeof ToursRoute
  '/umrah': typeof UmrahRoute
  '/visa': typeof VisaRoute
  '/admin/inquiries': typeof AdminInquiriesRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/packages': typeof AdminPackagesRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/visa-countries': typeof AdminVisaCountriesRoute
  '/admin/visa-requirements': typeof AdminVisaRequirementsRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/air-ticketing'
    | '/contact'
    | '/faq'
    | '/medical-tourism'
    | '/services'
    | '/tours'
    | '/umrah'
    | '/visa'
    | '/admin/inquiries'
    | '/admin/login'
    | '/admin/packages'
    | '/admin/settings'
    | '/admin/visa-countries'
    | '/admin/visa-requirements'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/air-ticketing'
    | '/contact'
    | '/faq'
    | '/medical-tourism'
    | '/services'
    | '/tours'
    | '/umrah'
    | '/visa'
    | '/admin/inquiries'
    | '/admin/login'
    | '/admin/packages'
    | '/admin/settings'
    | '/admin/visa-countries'
    | '/admin/visa-requirements'
    | '/admin'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/air-ticketing'
    | '/contact'
    | '/faq'
    | '/medical-tourism'
    | '/services'
    | '/tours'
    | '/umrah'
    | '/visa'
    | '/admin/inquiries'
    | '/admin/login'
    | '/admin/packages'
    | '/admin/settings'
    | '/admin/visa-countries'
    | '/admin/visa-requirements'
    | '/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AirTicketingRoute: typeof AirTicketingRoute
  ContactRoute: typeof ContactRoute
  FaqRoute: typeof FaqRoute
  MedicalTourismRoute: typeof MedicalTourismRoute
  ServicesRoute: typeof ServicesRoute
  ToursRoute: typeof ToursRoute
  UmrahRoute: typeof UmrahRoute
  VisaRoute: typeof VisaRoute
  AdminInquiriesRoute: typeof AdminInquiriesRoute
  AdminLoginRoute: typeof AdminLoginRoute
  AdminPackagesRoute: typeof AdminPackagesRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminVisaCountriesRoute: typeof AdminVisaCountriesRoute
  AdminVisaRequirementsRoute: typeof AdminVisaRequirementsRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/visa': {
      id: '/visa'
      path: '/visa'
      fullPath: '/visa'
      preLoaderRoute: typeof VisaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/umrah': {
      id: '/umrah'
      path: '/umrah'
      fullPath: '/umrah'
      preLoaderRoute: typeof UmrahRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tours': {
      id: '/tours'
      path: '/tours'
      fullPath: '/tours'
      preLoaderRoute: typeof ToursRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/medical-tourism': {
      id: '/medical-tourism'
      path: '/medical-tourism'
      fullPath: '/medical-tourism'
      preLoaderRoute: typeof MedicalTourismRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/air-ticketing': {
      id: '/air-ticketing'
      path: '/air-ticketing'
      fullPath: '/air-ticketing'
      preLoaderRoute: typeof AirTicketingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/visa-requirements': {
      id: '/admin/visa-requirements'
      path: '/admin/visa-requirements'
      fullPath: '/admin/visa-requirements'
      preLoaderRoute: typeof AdminVisaRequirementsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/visa-countries': {
      id: '/admin/visa-countries'
      path: '/admin/visa-countries'
      fullPath: '/admin/visa-countries'
      preLoaderRoute: typeof AdminVisaCountriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/admin/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/packages': {
      id: '/admin/packages'
      path: '/admin/packages'
      fullPath: '/admin/packages'
      preLoaderRoute: typeof AdminPackagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/admin/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/inquiries': {
      id: '/admin/inquiries'
      path: '/admin/inquiries'
      fullPath: '/admin/inquiries'
      preLoaderRoute: typeof AdminInquiriesRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AirTicketingRoute: AirTicketingRoute,
  ContactRoute: ContactRoute,
  FaqRoute: FaqRoute,
  MedicalTourismRoute: MedicalTourismRoute,
  ServicesRoute: ServicesRoute,
  ToursRoute: ToursRoute,
  UmrahRoute: UmrahRoute,
  VisaRoute: VisaRoute,
  AdminInquiriesRoute: AdminInquiriesRoute,
  AdminLoginRoute: AdminLoginRoute,
  AdminPackagesRoute: AdminPackagesRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminVisaCountriesRoute: AdminVisaCountriesRoute,
  AdminVisaRequirementsRoute: AdminVisaRequirementsRoute,
  AdminIndexRoute: AdminIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
